name: Build
on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ninja-build \
            meson
            
      - name: Setup and Build
        run: |
          meson setup build
          meson compile -C build
          
  macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          python -m pip install meson
          python -m pip install ninja
          
      - name: Setup and Build
        run: |
          meson setup build
          meson compile -C build
          
  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install build dependencies
        run: |
          python -m pip install meson
          python -m pip install ninja
          
      - name: Setup and Build
        run: |
          meson setup build
          meson compile -C build
